### PR TITLE
Fixing MBInstallHeaders to handle arbitrary-depth paths

### PR DESCRIPTION
**Pull request by tedbrandston**
libdigitizer was breaking because it used too-deep paths

### CODE REVIEW

**Comment by benfeltz** [comment]
Is that why it was building on Mac but not windows ? Path length?

**Comment by tedbrandston** [comment]
Ben: the path handling stuff was only for mac, which uses frameworks and keeps its headers in them. We were using the path as a stand-in for the framework name, and then had some headers that needed to be nested a directory deep. Nicholas 'fixed' this by splitting the paths and using the highest directory, but noted that it wouldn't work past two levels deep. Digitizer just added something that had to be three deep, and everything fell apart.

**Comment by benfeltz** [comment]
Thanks for the explanation

**Comment by nicholasbishop** [comment]
#publiclyshamed #onlyoffbyone #onlysodiligent

**Comment by tedbrandston** [comment]
Oh, man! Forgot this was an open repo. Hi Nicholas! How's things?

**Comment by nicholasbishop** [comment]
Hi Ted! Things are great! How're you?

**Comment by tedbrandston** [comment]
I saw this quote from John Darnielle and thought of you: 

> I was starting to hang with kids who were really hip — older kids than me. That was not something I was gonna put in front of these dudes. I was also into science fiction and fantasy. The fact that I was into unicorns and dragons? You know how important it is to not get off on the wrong foot with the people you respect in high school. You hide the stuff that’s important to you if it might possibly cause you friction, and that was me. I have a lot of shame about that. I sold out the unicorns. 

Things are pretty normal. Just me and Ryan, slowly switching things over to CMake. Generally improving Jenkins, testing frameworks, etc.

**Pull request merged**
